### ISSUE TITLE
Sealious.ResourceType is not a constructor

### ISSUE THREAD

**Issue by adwydman** [sealcode/sealious#271]
I just downloaded Sealious for development and tried to run `npm test` on both `alpha` and `test_development` branches. Both showed me this error:

```
C:\Users\anwi\Desktop\sealious\tests\unit-tests\resource-manager.test.js:10
        var listable = new Sealious.ResourceType({
                       ^

TypeError: Sealious.ResourceType is not a constructor
    at Object.module.exports.test_init (C:\Users\anwi\Desktop\sealious\tests\unit-tests\resource-manager.test.js:10:24)
    at Object.<anonymous> (C:\Users\anwi\Desktop\sealious\tests\test.js:35:36)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:
```

Was `Sealious.ResourceType` changed? My node version: v6.2.2

**Comment by adwydman** [comment]
Problem persists also on node version v.4.4.7

**Comment by kuba-orlik** [comment]
I don't think these branches are good to use. I suggest running `beta` :)
