### ISSUE TITLE
ChipManager was asked to return a chip of type `field_type` and name `color`, but it was not found

### ISSUE THREAD

**Issue by adwydman** [sealcode/sealious#272]
On a new Sealious for development instance there's a problem with `color` field-type:

```
10:43:39.723 - info: Starting all chips:
10:43:39.724 - info:    datastore:
10:43:39.724 - info:      ✓ tingodb
10:43:39.729 - info:    access_strategy:
10:43:39.729 - info:      ✓ id_starts_with_digit
10:43:39.729 - info:      ✓ noone
10:43:39.729 - info:      ✓ public
10:43:39.729 - info:      ✓ just_owner
10:43:39.730 - info:      ✓ test_access_strategy
10:43:39.730 - info:    field_type:
10:43:39.730 - info:      ✓ date
10:43:39.730 - info:      ✓ datetime
10:43:39.730 - info:      ✓ boolean
10:43:39.730 - info:      ✓ email
10:43:39.730 - info:      ✓ int
10:43:39.730 - info:      ✓ float
10:43:39.730 - info:      ✓ text
10:43:39.730 - info:      ✓ file
10:43:39.730 - info:      ✓ reference
10:43:39.730 - info:      ✓ test_field_type
10:43:39.730 - info:      ✓ rejecting_father
10:43:39.731 - info:      ✓ accepting_son
10:43:39.731 - info:      ✓ hesitant_daughter
10:43:39.731 - info:    resource_type:
10:43:39.731 - info:      ✓ user
10:43:39.731 - info:      ✓ chip_manager_tests_resource
10:43:39.731 - info:      ✓ testable
10:43:39.731 - info:    channel:
Unhandled rejection Error: ChipManager was asked to return a chip of type `field_type` and name `color`, but it was not found
    at new SealiousErrors.Error (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\lib\response\error.js:6:12)
    at new SealiousErrors.ValidationError (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\lib\response\error.js:21:12)
    at get_chip (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\lib\chip-types\chip-manager.js:111:10)
    at Object.module.exports.test_start (C:\Users\anwi\Desktop\sealious\tests\unit-tests\field-type.color.test.js:7:47)
    at C:\Users\anwi\Desktop\sealious\tests\test.js:23:35
    at tryCatcher (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\promise.js:244:10)
    at Async._drainQueue (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\anwi\AppData\Roaming\npm\node_modules\sealious\node_modules\bluebird\js\main\async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
10:43:39.812 - info: Sealious@0.6.24 is up-to-date.
```

The file `field_type.color.js` exists in the `base-chips` directory.

**Comment by kuba-orlik** [comment]
which Sealious version are you running?

**Comment by adwydman** [comment]
`6.2.2`

**Comment by adwydman** [comment]
It says in the bottom: `Sealious@0.6.24 is up-to-date`

**Comment by kuba-orlik** [comment]
Whops, you're right :) I guess it's because the field type is not being `require`d inside `base-chips/_base-chips.js`

**Comment by kuba-orlik** [comment]
It's been fixed during one of our recent changes.
