### ISSUE TITLE
Strange errors when running a regular app

### ISSUE THREAD

**Issue by adwydman** [sealcode/sealious#302]
I try to run FKA bookshop app, here are REST routes:

```
new Sealious.Collection({
    name: "books",
    fields: [
        {name: "author", type: "text", required: true},
        {name: "title", type: "text", required: true},
        {name: "year", type: "int", required: true},
        {name: "book", type: "file", required: false}
    ]
});

//Codes generation
www_server.route({
    method: "POST",
    path: "/api/v1/codes",
    handler: codePost
});

//Get particular code -- it returns
www_server.route({
    method: "GET",
    path: "/api/v1/codes/{code}",
    handler: codeGet
});

//Get all codes
www_server.route({
    method: "GET",
    path: "/api/v1/codes",
    handler: codesGet
});

www_server.route({
    method: "DELETE",
    path: "/api/v1/codes/{code}",
    handler: codeDelete
});
```

When I try to `GET api/v1/books`:

```
{
  "message": "No child subject with key 'books' in RootSubject",
  "type": "bad_subject",
  "data": {}
}
```

When I try to `GET api/v1/codes` I get status code 500 and error:

```
23:22:26.206 - error:  TypeError: Cannot read property 'SealiousSession' of undefined
    at Chip.www_server.get_context (/home/adrian/Documents/fka-bookshop/node_modules/sealious-channel-rest/node_modules/sealious-www-server/define/channel.www_server.js:111:32)
    at /home/adrian/Documents/fka-bookshop/app/codesGet.js:3:36
    at /home/adrian/Documents/fka-bookshop/node_modules/sealious-channel-rest/node_modules/sealious-www-server/define/channel.www_server.js:126:10
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/adrian/Documents/fka-bookshop/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

**Comment by arkadiusz-wieczorek** [comment]
Which version of sealious are you using?

**Comment by adwydman** [comment]
FML... ok, thanks...

**Comment by adwydman** [comment]
Okay, the problem is solved for `books`, but it persists for `codes`, even when I changed the route. The error is still the same.

**Comment by arkadiusz-wieczorek** [comment]
Yes, because `codes` isn't a collection. I think that you have to check declaration `www_server.route` in currently version of sealious-www-server. Unfortunately sealious-www-server requires rewrite. Probably  `path: "/api/v1/codes" is overlooked in declaration process.

**Comment by arkadiusz-wieczorek** [comment]
Why you didn't use collection structure for codes?

**Comment by adwydman** [comment]
Because their behaviour is not typical and it required a custom handler.

**Comment by arkadiusz-wieczorek** [comment]
Do you have this declaration in main.js: `www_server = Sealious.ChipManager.get_chip("channel", "www_server");`?

**Comment by kuba-orlik** [comment]
As we talked afk today, please use Collections for codes. Disable the default `create` route with an access strategy (`create: "noone"`) and create a custom route only for creating the codes. Cheers!

**Comment by kuba-orlik** [comment]
Issues moved do Sealcode's phabricator: https://hub.sealcode.org/project/view/11/
